apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-tls
  namespace: default
spec:
  secretName: wisecow-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: wisecow.local
  dnsNames:
    - wisecow.local
  duration: 8760h # Valid for 1 year
  renewBefore: 360h # Renew certificate before 15 days of expiry
