name: Deploy to Local Kubernetes

on:
  workflow_run:
    workflows: ["CI Pipeline for Docker Image"]  # Match your first workflow's name
    types:
      - completed

  push:
    branches: 
      - main
    paths:
      - 'k8/**'

# .github/workflows/deploy-on-arc.yml
jobs:
  kubernetes-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 4: Verify kubectl can access your cluster
      - name: Check Kubernetes cluster
        run: kubectl cluster-info

      - name: Conditionally install cert-manager
        run: |
           if (-not (kubectl get ns cert-manager -ErrorAction SilentlyContinue)) {
            Write-Host "Installing cert-manager..."
            kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.10.0/cert-manager.yaml
            } else {
            Write-Host "cert-manager already installed."
            } 
      - name: Conditionally install NGINX ingress controller
        run: |
              if (-not (kubectl get ns ingress-nginx -ErrorAction SilentlyContinue)) {
                Write-Host "Installing ingress-nginx..."
                kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/cloud/deploy.yaml
              } else {
                Write-Host "Ingress NGINX already installed."
              }
      - name: Reapply Kubernetes manifests until ingress controller is ready
        run: |
            # Set the duration for retries and interval between tries
            $limit = 600  # 10 minutes
            $interval = 30  # Reapply every 30 seconds
            $end = (Get-Date).AddSeconds($limit)
  
            # Loop to reapply the manifest until the time limit is reached
            while ((Get-Date) -lt $end) {
  
                # Check if ingress-nginx pods are ready
                $podsReady = kubectl get pods -n ingress-nginx --field-selector=status.phase=Running
                if ($podsReady) {
                    Write-Host "Ingress controller is ready!"
                    break
                }
  
                Write-Host "Ingress controller is not ready, retrying..."
                Start-Sleep -Seconds $interval
            }
      - name: Deploy to Kubernetes
        run: |
          $startTime = Get-Date
          $timeout = New-TimeSpan -Minutes 5
          $success = $false
          while ((Get-Date) - $startTime -lt $timeout) {
            try {
              # Attempt to apply the Kubernetes resources
              kubectl apply -f k8/
              $success = $true
              Write-Host "Successfully applied Kubernetes resources."
              break
            } catch {
              Write-Host "Attempt failed. Retrying..."
            }
            Start-Sleep -Seconds 10  # Wait 10 seconds before retrying
          }

          if (-not $success) {
            Write-Host "Deployment failed after 5 minutes."
            exit 1  # Fail the step after the timeout
          }
      - name: Modify Hosts File
        run: |
            $hostsFile = "C:\Windows\System32\drivers\etc\hosts"
            $entry = "127.0.0.1   wisecow.local"
  
            # Check if the hosts file exists
            if (-not (Test-Path $hostsFile)) {
              Write-Host "Hosts file does not exist."
              exit 1
            }
  
            # Read the hosts file content and check if the entry already exists
            $hostsContent = Get-Content -Path $hostsFile
  
            if ($hostsContent -contains $entry) {
              Write-Host "Entry already exists in the hosts file."
            } else {
              # Add the entry to the hosts file if it doesn't exist
              Add-Content -Path $hostsFile -Value $entry
              Write-Host "Entry added to the hosts file."
            }

