name: Deploy to Local Kubernetes

on:
  workflow_run:
    workflows: ["CI Pipeline for Docker Image"]  # Match your first workflow's name
    types:
      - completed

  push:
    branches: 
      - main
    paths:
      - 'k8/**'

# .github/workflows/deploy-on-arc.yml
jobs:
  kubernetes-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 4: Verify kubectl can access your cluster
      - name: Check Kubernetes cluster
        run: kubectl cluster-info

      - name: Conditionally install cert-manager
        shell: bash
        run: |
          if ! kubectl get ns cert-manager &> /dev/null; then
            echo "Installing cert-manager..."
            kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
          else
            echo "cert-manager already installed."
          fi

      - name: Conditionally install NGINX ingress controller
        shell: bash
        run: |
          if ! kubectl get ns ingress-nginx &> /dev/null; then
            echo "Installing ingress-nginx..."
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/cloud/deploy.yaml
          else
            echo "Ingress NGINX already installed."
          fi

      - name: Deploy to Kubernetes
        shell: bash
        run: kubectl apply -f k8/

