name: Deploy to Local Kubernetes

on:
  workflow_run:
    workflows: ["CI Pipeline for Docker Image"]  # Match your first workflow's name
    types:
      - completed

  push:
    branches: 
      - main
    paths:
      - 'k8/**'

# .github/workflows/deploy-on-arc.yml
jobs:
  kubernetes-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 4: Verify kubectl can access your cluster
      - name: Check Kubernetes cluster
        run: kubectl cluster-info

      - name: Conditionally install cert-manager
        run: |
           if (-not (kubectl get ns cert-manager -ErrorAction SilentlyContinue)) {
            Write-Host "Installing cert-manager..."
            kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
            } else {
            Write-Host "cert-manager already installed."
            } 

      - name: Conditionally install NGINX ingress controller
        run: |
          if (-not (kubectl get ns cert-manager -ErrorAction SilentlyContinue)) {
          Write-Host "Installing cert-manager..."
          kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
          } else {
          Write-Host "cert-manager already installed."
          }

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8/

